wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1630056754
    t:
      1:
      - 3
      2:
      - 3
      4: 3.9.5
      5: 0.12.0
      8:
      - 3
      - 5
